---
- hosts: myhosts
  connection: local
  gather_facts: False
  tasks:
    - name: Validate server authentication input provided by user
      fail:
        msg: "username/password or cert_file/key_file or auth_token is mandatory"
      when:
        - (username is not defined or password is not defined) and (cert_file is not defined or key_file is not defined) and (auth_token is not defined)

    - name: Fail when more than one valid authentication method is provided
      fail:
        msg: "Only one authentication method is allowed. Provide either username/password or cert_file/key_file or auth_token."
      when:
        - ((username is defined or password is defined) and (cert_file is defined or key_file is defined) and auth_token is defined) or
          ((username is defined or password is defined) and (cert_file is defined or key_file is defined)) or
          ((username is defined or password is defined) and auth_token is defined) or
          ((cert_file is defined or key_file is defined) and auth_token is defined)

    - name: Check whether maintenance window is provided
      set_fact:
        maintenance_window_flag : "{{ True if maintenance_window_details is defined else False}}"

    - name: Perform firmware upgrade on the server using install set when username and password are defined
      block:
        - name: Block for firmware upgradation without maintenance window
          block:
            - name: Perform firmware upgrade on the server without maintenance window using install set when username and password are defined
              ilo_firmware:
                category: UpdateService
                command: UpdateFirmwareThroughInstallSet
                baseuri: "{{ baseuri }}"
                username: "{{ username }}"
                password: "{{ password }}"
                install_set_attributes: "{{ install_set_attributes }}"
              register: firmware_upgrade_rsp

            - name: Collecting server IP, task ID(s) and URL details when username and password are defined
              set_fact:
                server_rsp_details:
                  Server: "{{ baseuri }}"
                  Tasks: "{{ firmware_upgrade_rsp['ilo_firmware']['UpdateFirmwareThroughInstallSet']['msg'] }}"

            - name: Firmware upgrade status when username and password are defined
              debug:
                msg: "{{ server_rsp_details }}"
          when: not maintenance_window_flag

        - name: Block for firmware upgradation with maintenance window
          block:
            - name: Perform firmware upgrade on the server with maintenance window using install set when username and password are defined
              ilo_firmware:
                category: UpdateService
                command: UpdateFirmwareThroughInstallSet
                baseuri: "{{ baseuri }}"
                username: "{{ username }}"
                password: "{{ password }}"
                install_set_attributes: "{{ install_set_attributes }}"
                maintenance_window_details: "{{ maintenance_window_details }}"
              register: firmware_upgrade_rsp

            - name: Collecting server IP, task ID(s) and URL details when username and password are defined
              set_fact:
                server_rsp_details:
                  Server: "{{ baseuri }}"
                  Tasks: "{{ firmware_upgrade_rsp['ilo_firmware']['UpdateFirmwareThroughInstallSet']['msg'] }}"

            - name: Firmware upgrade status when username and password are defined
              debug:
                msg: "{{ server_rsp_details }}"
          when: maintenance_window_flag

      when: username is defined and password is defined

    - name: Perform firmware upgrade on the server using install set when cert_file and key_file are defined
      block:
        - name: Block for firmware upgradation without maintenance window
          block:
            - name: Perform firmware upgrade on the server without maintenance window using install set when cert_file and key_file are defined
              ilo_firmware:
                category: UpdateService
                command: UpdateFirmwareThroughInstallSet
                baseuri: "{{ baseuri }}"
                cert_file: "{{ cert_file }}"
                key_file: "{{ key_file }}"
                install_set_attributes: "{{ install_set_attributes }}"
              register: firmware_upgrade_rsp

            - name: Collecting server IP, task ID(s) and URL details when cert_file and key_file are defined
              set_fact:
                server_rsp_details:
                  Server: "{{ baseuri }}"
                  Tasks: "{{ firmware_upgrade_rsp['ilo_firmware']['UpdateFirmwareThroughInstallSet']['msg'] }}"

            - name: Firmware upgrade status when cert_file and key_file are defined
              debug:
                msg: "{{ server_rsp_details }}"
          when: not maintenance_window_flag

        - name: Block for firmware upgradation with maintenance window
          block:
            - name: Perform firmware upgrade on the server with maintenance window using install set when cert_file and key_file are defined
              ilo_firmware:
                category: UpdateService
                command: UpdateFirmwareThroughInstallSet
                baseuri: "{{ baseuri }}"
                cert_file: "{{ cert_file }}"
                key_file: "{{ key_file }}"
                install_set_attributes: "{{ install_set_attributes }}"
                maintenance_window_details: "{{ maintenance_window_details }}"
              register: firmware_upgrade_rsp

            - name: Collecting server IP, task ID(s) and URL details when cert_file and key_file are defined
              set_fact:
                server_rsp_details:
                  Server: "{{ baseuri }}"
                  Tasks: "{{ firmware_upgrade_rsp['ilo_firmware']['UpdateFirmwareThroughInstallSet']['msg'] }}"

            - name: Firmware upgrade status when cert_file and key_file are defined
              debug:
                msg: "{{ server_rsp_details }}"
          when: maintenance_window_flag

      when: cert_file is defined and key_file is defined

    - name: Perform firmware upgrade on the server using install set when auth token is defined
      block:
        - name: Block for firmware upgradation without maintenance window
          block:
            - name: Perform firmware upgrade on the server without maintenance window using install set when auth token is defined
              ilo_firmware:
                category: UpdateService
                command: UpdateFirmwareThroughInstallSet
                baseuri: "{{ baseuri }}"
                auth_token: "{{ auth_token }}"
                install_set_attributes: "{{ install_set_attributes }}"
              register: firmware_upgrade_rsp

            - name: Collecting server IP, task ID(s) and URL details when auth token is defined
              set_fact:
                server_rsp_details:
                  Server: "{{ baseuri }}"
                  Tasks: "{{ firmware_upgrade_rsp['ilo_firmware']['UpdateFirmwareThroughInstallSet']['msg'] }}"

            - name: Firmware upgrade status when auth token is defined
              debug:
                msg: "{{ server_rsp_details }}"
          when: not maintenance_window_flag

        - name: Block for firmware upgradation with maintenance window
          block:
            - name: Perform firmware upgrade on the server with maintenance window using install set when auth token is defined
              ilo_firmware:
                category: UpdateService
                command: UpdateFirmwareThroughInstallSet
                baseuri: "{{ baseuri }}"
                auth_token: "{{ auth_token }}"
                install_set_attributes: "{{ install_set_attributes }}"
                maintenance_window_details: "{{ maintenance_window_details }}"
              register: firmware_upgrade_rsp

            - name: Collecting server IP, task ID(s) and URL details when auth token is defined
              set_fact:
                server_rsp_details:
                  Server: "{{ baseuri }}"
                  Tasks: "{{ firmware_upgrade_rsp['ilo_firmware']['UpdateFirmwareThroughInstallSet']['msg'] }}"

            - name: Firmware upgrade status when auth token is defined
              debug:
                msg: "{{ server_rsp_details }}"
          when: maintenance_window_flag

      when: auth_token is defined
