---
- hosts: myhosts
  connection: local
  name: Install Package
  gather_facts: False
  vars:
    remote_file_path: /path/to/remote/file
    local_file_path: /path/to/local/file
    filename: package_name

  tasks:
    #Need to install ansible-galaxy collection install ansible.posix
    - name: Copy file to remote machine
      ansible.builtin.expect:
        command: >
          scp {{ local_file_path }}
          {{ username }}@{{ baseuri }}:{{ remote_file_path }}
        responses:
          ".*password.*": "{{ password }}\n"
          ".*Are you sure you want to continue connecting.*": "yes\n"
        echo: yes
      register: scp_output

    - name: Installing Package
      ilo_fwupdate_command:
        category: RLCP
        command: PackageInstall
        baseuri: "{{ baseuri }}"
        username: "{{ username }}"
        password: "{{ password }}"
        remote: "{{ remote_file_path }}"
        install_filename: "{{ filename }}"
