---
- hosts: myhosts
  connection: local
  gather_facts: False
  tasks:
    - name: Validate input provided by user
      fail:
        msg: "username/password or cert_file/key_file or auth_token is mandatory"
      when:
        - (username is not defined or password is not defined) and (cert_file is not defined or key_file is not defined) and (auth_token is not defined)

    - name: Fail when more than one valid authentication method is provided
      fail:
        msg: "Only one authentication method is allowed. Provide either username/password or cert_file/key_file or auth_token."
      when:
        - ((username is defined or password is defined) and (cert_file is defined or key_file is defined) and auth_token is defined) or
          ((username is defined or password is defined) and (cert_file is defined or key_file is defined)) or
          ((username is defined or password is defined) and auth_token is defined) or
          ((cert_file is defined or key_file is defined) and auth_token is defined)

    - name: Import Trusted CA when username and password are defined
      block:
        - ilo_security:
            category: Manager
            command: ImportTrustedCA
            baseuri: "{{ baseuri }}"
            username: "{{ username }}"
            password: "{{ password }}"
            ca_file: "{{ ca_file }}"
          register: result

        - name: Status
          debug:
            msg: "{{ result }}"

      when: username is defined and password is defined

    - name: Import Trusted CA when auth_token is defined
      block:
        - ilo_security:
            category: Manager
            command: ImportTrustedCA
            baseuri: "{{ baseuri }}"
            auth_token: "{{ auth_token }}"
            ca_file: "{{ ca_file }}"
          register: result

        - name: Status
          debug:
            msg: "{{ result }}"

      when: auth_token is defined