---
- hosts: myhosts
  connection: local
  gather_facts: False
  tasks:
    - name: Validate server authentication input provided by user
      fail:
        msg: "username/password or auth_token is mandatory"
      when:
        - (username is not defined or password is not defined) and (auth_token is not defined)

    - name: Fail when more than one valid authentication method is provided
      fail:
        msg: "Only one authentication method is allowed. Provide either username/password or auth_token."
      when:
        - ((username is defined or password is defined) and auth_token is defined)

    - name: Map User Certificate when username and password are defined
      block:
        - ilo_security:
            category: Manager
            command: MapUserCertificate
            baseuri: "{{ baseuri }}"
            username: "{{ username }}"
            password: "{{ password }}"
            user_cert_file: "{{ user_cert_file }}"
          register: result

        - name: Status
          debug:
            msg: "{{ result }}"

      when: username is defined and password is defined

    - name: Map User Certificate when auth_token is defined
      block:
        - ilo_security:
            category: Manager
            command: MapUserCertificate
            baseuri: "{{ baseuri }}"
            auth_token: "{{ auth_token }}"
            username: "{{ username }}"
            user_cert_file: "{{ user_cert_file }}"
          register: result

        - name: Status
          debug:
            msg: "{{ result }}"

      when: auth_token is defined
