---
- hosts: myhosts
  connection: local
  name: Get Boot Override
  gather_facts: False
  # vars_files: iLO_redfish.yml

  vars:
    datatype: BootOverride

  tasks:

  - name: Define output file
    include_tasks: create_output_file.yml

  - name: Create session
    community.general.redfish_command:
      category: Sessions
      command: CreateSession
      baseuri: "{{ baseuri }}"
      username: "{{ username }}"
      password: "{{ password }}"
    register: result

  - name: Get Boot Override information
    community.general.redfish_info:
      category: Systems
      command: GetBootOverride
      baseuri: "{{ baseuri }}"
      # username: "{{ username }}"
      # password: "{{ password }}"
      auth_token: "{{ result.session.token }}"
    register: result_ovr

  - name: Copy results to output file
    copy:
      content: "{{ result_ovr | to_nice_json }}"
      dest: "{{ template }}.json"

  - name: Delete session using security token created by CreateSession above
    community.general.redfish_command:
      category: Sessions
      command: DeleteSession
      baseuri: "{{ baseuri }}"
      auth_token: "{{ result.session.token }}"
      session_uri: "{{ result.session.uri }}"
