---
- hosts: myhosts
  connection: local
  name: Set one-time BIOS boot device
  gather_facts: False
  # vars_files: iLO_redfish.yml

  # ONLY WORKS IN LEGACY BIOS MODE!
  #
  # Bootdevice options include: None, Pxe, Cd, Floppy, Hdd, BiosSetup,
  # Utilities, UefiTarget & SDCard.

  vars:
    - bootdevice: Pxe

  tasks:
    - name: Create session
      community.general.redfish_command:
        category: Sessions
        command: CreateSession
        baseuri: "{{ baseuri }}"
        username: "{{ username }}"
        password: "{{ password }}"
      register: result

    - name: Set one-time boot device to {{ bootdevice }}
      community.general.redfish_command:
        category: Systems
        command: SetOneTimeBoot
        bootdevice: "{{ bootdevice }}"
        baseuri: "{{ baseuri }}"
        # username: "{{ username }}"
        # password: "{{ password }}"
        auth_token: "{{ result.session.token }}"
      register: bios_onetimeboot

    - name: Delete session using security token created by CreateSession above
      community.general.redfish_command:
        category: Sessions
        command: DeleteSession
        baseuri: "{{ baseuri }}"
        auth_token: "{{ result.session.token }}"
        session_uri: "{{ result.session.uri }}"
